### ISSUE TITLE
Use Submodule for vcf2maf

### ISSUE THREAD

**Issue by kellrott** [covingto/pancanmafmerge#1]
Rather then copy-paste in the entire project, try using submodules: https://git-scm.com/docs/git-submodule

**Comment by covingto** [comment]
Yeh but I had to make some custom changes to vcf2maf. And wanted everything
in one place.

**Comment by kellrott** [comment]
Can we get those changes submitted back to the original vcf2maf project?

**Comment by covingto** [comment]
Cyriac didn't want to incorporate some of them. I could implement the
functionality elsewhere as a post processing step but in the interest of
time just forked the code. Cyriac implemented some of the changes in his
repo.

**Comment by ckandoth** [comment]
The issues you originally forked and fixed, were handled in `vcf2maf v1.6.6`. Can you bullet out the remaining edits in the fork? Are they useful to MC3?

**Comment by covingto** [comment]
One is to remove alleles that are not in the genotype. Others are;
Flag to skip VEP and just trust the VCF
Preset missing data with .
Allow a pull through of VCF info fields, fields can be listed and they will
appear in the output MAF.

**Comment by covingto** [comment]
OK, forked vcf2maf and added as a submodule.  Cyriac can pull the changes over at his convenience and I can pull from his repo should changes be required.  I think Cyriac can also modify covingto/vcf2maf.git if that is more convenient
