### ISSUE TITLE
Chrom naming issues in MuTect VCFs

### ISSUE THREAD

**Issue by ckandoth** [covingto/pancanmafmerge#8]
In MuTect VCFs uploaded by Broad, some non-autosomal chromosomes are named with an enclosing `<>`. Here are a few examples...

```
<GL000192.1>
<GL000193.1>
<GL000194.1>
<M>
```

In the current workflow, `vcf2maf` is going to skip these calls during annotation, because they don't match anything in the GRCh37 reference FASTA. For the first pass MAF, skipping calls in these non-autosomal chroms should be OK.

Otherwise, the fix is to simply remove the enclosing `<>` and also rename `M` to `MT`.

::NOTE:: Both MuTect and Indelocator VCFs have the following line in the header:

```
##reference=<ID=hg19,source="http://www.broadinstitute.org/ftp/pub//seq/references/Homo_sapiens_assembly19.fasta">
```

The ID says `hg19`, but the fasta at that link is actually GRCh37. This VCF header line is likely hard-coded, rather than what was actually used to generate this VCF.

**Comment by covingto** [comment]
Not sure how sort VCF would handle these. Have yet to see
an example or error but will look.
