### ISSUE TITLE
vcf2maf - ExAC based annotations not in resulting MAF

### ISSUE THREAD

**Issue by ckandoth** [covingto/pancanmafmerge#9]
Might be something to do with how VEP is set up at HGSC. If the ExAC VCF is not in the folder pointed to by `--vep-data`, then vcf2maf will ignore it altogether rather than complain with an error. Complete instructions to set up VEP v82 or v84 are in these gists:
https://gist.github.com/ckandoth/9d6ad6a7fd3b058e5bc98a1ce884641a
https://gist.github.com/ckandoth/57d189f018b448774704d3b2191720a6

**Comment by covingto** [comment]
Thanks for this report but the main purpose of the pancanmafmerge project is to merge variants and generate a minimal MAF that conforms as best as possible to the 32 column MAF file outlined by TCGA (https://wiki.nci.nih.gov/display/TCGA/Mutation+Annotation+Format+%28MAF%29+Specification).  That document actually references a 34 column MAF with columns for the uuids of the tumor and normal, which I don't think are accounted for in this project.

While there are extra annotations above what is detailed in the specification most of those are "side effects" of generating fields that match the required annotations (DBVS in place of dbSNP_Val_Status).  Those fields are still separate from their location in the MAF spec as of this version and it would be a good idea to write further modules to move those into the correct location as a post processing step, but that hasn't been done yet.

There are likely many fields that groups would like to have annotated into the maf file that they work with and many very good annotators, but extra annotations are beyond the scope of this project.

**Comment by ckandoth** [comment]
Per that argument, here's a list of all the non-34 MAF columns that you're arguing are non-essential:

```text
35. HGVSc - the coding sequence of the variant in HGVS recommended format
36. HGVSp - the protein sequence of the variant in HGVS recommended format
37. HGVSp_Short - Same as HGVSp, but using 1-letter amino-acid codes
38. Transcript_ID - transcript onto which the consequence of the variant has been mapped
39. Exon_Number - the exon number (out of total number)
40. t_depth - read depth across this locus in tumor BAM
41. t_ref_count - read depth supporting the reference allele in tumor BAM
42. t_alt_count - read depth supporting the variant allele in tumor BAM
43. n_depth - read depth across this locus in normal BAM
44. n_ref_count - read depth supporting the reference allele in normal BAM
45. n_alt_count - read depth supporting the variant allele in normal BAM
```

I only made this issue for tracking purposes. I agree it's low priority, and we'll get to it, when we get to it. ExAC annotation will be like as a panel-of-normals for filtering out germline sites before public release.

**Comment by covingto** [comment]
I might argue that those should be added to the MAF spec I personally find many of them to be quite useful.  I should have been more precise earlier, the working group did outline additional fields to be added, specifically those that you mentioned and that was agreed upon as information to extract from the VCF files which could only be done at the stage where this project fits into the overall workflow (columns 40-45).  

I would prefer that variant annotations (eg 35-39, and even 1, 2, 14, and 15 of the MAF spec) be handled in a separate project, perhaps pancanmafannotation.  pancanmafmerge still doesn't annotate column 2 properly and the dbsnp validation status does not incorporate if the variant is an alternate allele or not (VEP was run without the --check-allele flag) just to list a few things that should be tidied up.  I view the purpose of this project to be to merge the VCF files to make a "minimal" (plus the extra vcf genotype information that was deemed to be critical [cols 40-45]) MAF file.  

I'm not arguing that ExAC isn't useful or that any annotation is not useful.  I would just like for those to be separate projects from this one.  I would also prefer that any post-MAF filtering be in a separate project as well.  I see realize that we do have several filtering modules in place but those are to correct variants in specific callers, largely at the request of the caller authors.  This isn't a matter of the utility of these activities but rather trying to constrain the scope of the project and to have a more modular organization to the overall pancan MAF effort.
